name: Unicorn Brain Automation Tests

on:
  push:
    branches:
      - main

jobs:
  unicorn-brain-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Fetch new test cases in Postman Collection
        env:
          COLLECTION_URL: ${{ secrets.COLLECTION_URL }}
          POSTMAN_ACCESS_KEY: ${{ secrets.POSTMAN_ACCESS_KEY }}
        run: |
          curl -o version1.json -L "${COLLECTION_URL}?access_key=${POSTMAN_ACCESS_KEY}"

      - name: Format JSON
        run: |
          jq . version1.json > version1_formatted.json
          mv version1_formatted.json version1.json

      - name: Run Collection with OAuth2.0
        env:
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        run: |
          newman run version1.json \
            -e non-prod.postman_environment.json \
            --env-var "client_secret=$CLIENT_SECRET" \
            -r htmlextra --reporter-htmlextra-export myReport.html --reporter-htmlextra-darkTheme

      - name: Send HTML Report Link to Slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          cat myReport.html         
          payload='{
            "text": "Newman Test Report",
            "attachments": [
              {
                "fallback": "Unicorn Brain Test Report",
                "color": "#36a64f",
                "title": "Unicorn Brain Test Report",
                "title_link": "myReport.html"           
              }
            ]
          }'

          # Send the payload to Slack
          curl -X POST -H 'Content-type: application/json' --data "$payload" "$SLACK_WEBHOOK_URL"
