name: Unicorn Brain Automation Tests
on: push

jobs:
  unicorn-brain-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Node Installation
        uses: actions/setup-node@v1
        with:
          node-version: '18'

      - name: Global Newman
        run: |
          npm install -g newman

      - name: Fetch new test cases in Postman Collection
        env:
          COLLECTION_URL: ${{ secrets.COLLECTION_URL }}
          POSTMAN_ACCESS_KEY: ${{ secrets.POSTMAN_ACCESS_KEY }}
        run: |
          curl -o version1.json -L ${COLLECTION_URL}access_key=${POSTMAN_ACCESS_KEY}

      - name: Format JSON
        run: |
          jq . version1.json > version1_formatted.json
          mv version1_formatted.json version1.json

      - name: Run Collection with OAuth2.0
        env:
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        run: |
          newman run version1.json \
            -e non-prod.postman_environment.json \
            --env-var "client_secret=$CLIENT_SECRET" \
            --reporters htmlextra \
            --reporter-htmlextra-export docs/report.html

      - name: Send report to Slack
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"Newman HTML report", "attachments":[{"text":"Postman test report","fallback":"Report Link","color":"#36a64f","attachment_type":"default","actions":[{"type":"button","text":"View Report","url":"https://$GITHUB_REPOSITORY.github.io/docs/report.html"}]}]}' \
          ${{ secrets.SLACK_WEBHOOK_URL }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Upload HTML report as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: newman-html-report
          path: report.html
