name: Newman API Tests
on: push
jobs:
  unicorn-brain-api:
    name: 'Run tests'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install Newman
        run: npm install -g newman
      - name: Install Newman Reporter
        run: npm install -g newman-reporter-htmlextra

      - name: Run Collection with OAuth2.0
        env:
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        run: |
          newman run unicorn-brain-2.0.postman_collection.json \
            -e non-prod.postman_environment.json \
            --env-var "client_secret=$CLIENT_SECRET" \
            --reporters htmlextra

      - name: Upload HTML Report
        uses: actions/upload-artifact@v2
        with:
          name: newman-reports
          path: newman/    

      - name: Print report
        run: |
          cat newman/*.*    

      - name: Create Status Check based on Postman Results
        id: process-postman
        uses: im-open/process-postman-test-results@v2.1.5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          results-file: ${{ github.workspace }}/newman/your-html-report-file.html
          report-name: 'Postman ${{ github.run_number }}'
          create-status-check: true
          create-pr-comment: false
          update-comment-if-one-exists: false
          ignore-test-failures: true
          timezone: 'america/denver'

      - name: Fail on Test Failures
        if: steps.process-postman.outcome == 'failure'
        run: |
          echo "There were Postman test failures."
          exit 1
